//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Czasopismo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Czasopismo()
        {
            this.Wypozyczenia_Czasopisma = new HashSet<Wypozyczenia_Czasopisma>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Wprowadü Tytu≥")]
        [StringLength(50)]
        public string Tytul { get; set; }
        [Required(ErrorMessage = "Wprowadü ISBN")]
        [StringLength(17, MinimumLength = 13)]
        public string ISBN { get; set; }
        [Required]
        public Nullable<int> Strony { get; set; }
        [Required]
        public Nullable<int> ID_Wydawcy { get; set; }
        public Nullable<int> ID_Autora { get; set; }
        [Required(ErrorMessage = "Wprowadü stan magazynowy")]
        public Nullable<int> Stan_Magazynowy { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Wydawca Wydawca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia_Czasopisma> Wypozyczenia_Czasopisma { get; set; }
    }
}
