//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wiadomosci
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "WprowadŸ treœæ wiadomoœci")]
        [StringLength(200, MinimumLength = 13)]
        public string Tresc { get; set; }
        public Nullable<int> ID_Czytelnika { get; set; }
    
        public virtual Czytelnik Czytelnik { get; set; }
    }
}
